[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "max-age=31536000"

# Cache fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    cache-control = "max-age=31536000"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"